# Generated by Django 4.0.4 on 2022-04-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_recipe_description_recipe_directions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='recipe',
            new_name='recipetitle',
        ),
    ]
