# Generated by Django 4.0.4 on 2022-04-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_recipe_recipeingredients_recipetitle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredients',
            new_name='RecipeIngredient',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipetitle',
            new_name='recipe',
        ),
    ]
